# Generated by Django 5.0.3 on 2024-03-20 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=45)),
                ('monto', models.FloatField()),
                ('fecha_gasto', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Tamaño',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('cantidad', models.IntegerField()),
                ('precio', models.FloatField()),
                ('tamaño', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distAvicola.tamaño')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio_final', models.FloatField()),
                ('fecha', models.DateField()),
                ('producto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distAvicola.producto')),
            ],
        ),
    ]
