# Generated by Django 5.0.3 on 2024-04-25 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distAvicola', '0004_detalleventas_lote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas',
            name='nombre',
            field=models.CharField(default=1, max_length=45),
            preserve_default=False,
        ),
    ]
